# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kh < Formula
  desc "Official CLI for KeyHarbour — self-hosted Terraform state backend"
  homepage "https://keyharbour.ca"
  version "0.8.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/KeyHarbour/cli/releases/download/v0.8.6/kh_0.8.6_darwin_amd64.tar.gz"
      sha256 "589c5a333cdbfcff4b6626c025a6be04060cf9b045b1d67cfd932efb35a619ac"

      define_method(:install) do
        bin.install "kh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/KeyHarbour/cli/releases/download/v0.8.6/kh_0.8.6_darwin_arm64.tar.gz"
      sha256 "639670bfba010a5edde1da082932a73bcedf3c224896720bc6adc9305cfc680b"

      define_method(:install) do
        bin.install "kh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/KeyHarbour/cli/releases/download/v0.8.6/kh_0.8.6_linux_amd64.tar.gz"
      sha256 "1d70c0e929d8e55a1919ef6e6f898421439cb1610340b04f259ef944ce20cf1f"
      define_method(:install) do
        bin.install "kh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/KeyHarbour/cli/releases/download/v0.8.6/kh_0.8.6_linux_arm64.tar.gz"
      sha256 "9bdf5225ba400641e9eb171d5126893af62005f99356fd69243e81ab0c9b69b2"
      define_method(:install) do
        bin.install "kh"
      end
    end
  end

  test do
    system "#{bin}/kh", "--version"
  end
end
