# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kh < Formula
  desc "Official CLI for KeyHarbour — self-hosted Terraform state backend"
  homepage "https://keyharbour.ca"
  version "0.8.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/KeyHarbour/kh/releases/download/v0.8.6/kh_0.8.6_darwin_amd64.tar.gz"
      sha256 "c4384408a371ccf90cb1e246bbed1bc6078ffa8a495ca6935d4bec2c4c6bca50"

      define_method(:install) do
        bin.install "kh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/KeyHarbour/kh/releases/download/v0.8.6/kh_0.8.6_darwin_arm64.tar.gz"
      sha256 "fa4ff8b1eec52124755575268de730bad1154e77bd48486b833892ee1dd397f3"

      define_method(:install) do
        bin.install "kh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/KeyHarbour/kh/releases/download/v0.8.6/kh_0.8.6_linux_amd64.tar.gz"
      sha256 "ae75ac216dccd4a4339dcf83e257fdea467b59ec0e2a01d71292208c2bd39b14"
      define_method(:install) do
        bin.install "kh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/KeyHarbour/kh/releases/download/v0.8.6/kh_0.8.6_linux_arm64.tar.gz"
      sha256 "03f4275aadd1c70051cc77618b08f7afc5dceb89ac3e51348fcd0dbc5d025494"
      define_method(:install) do
        bin.install "kh"
      end
    end
  end

  test do
    system "#{bin}/kh", "--version"
  end
end
