# This file was generated by GoReleaser. DO NOT EDIT.
cask "kh" do
  version "1.9.1"

  on_macos do
    on_intel do
      url "https://github.com/KeyHarbour/kh/releases/download/v#{version}/kh_#{version}_darwin_amd64.tar.gz"
      sha256 "580c6c90fd29e85fe8dc4123c6b37b919d2c92ee4b07252da68d1229e50f9124"
      rename "kh_1.9.1_darwin_amd64/kh", "kh"
    end
    on_arm do
      url "https://github.com/KeyHarbour/kh/releases/download/v#{version}/kh_#{version}_darwin_arm64.tar.gz"
      sha256 "cbc81b4432b9c259db03cbce804474c43b68c651aee4e706156dd6fae7c91817"
      rename "kh_1.9.1_darwin_arm64/kh", "kh"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/KeyHarbour/kh/releases/download/v#{version}/kh_#{version}_linux_amd64.tar.gz"
      sha256 "9d47cab880abda9542df9e6741a6e4efb078a60e77fc458872b87136cda1f665"
      rename "kh_1.9.1_linux_amd64/kh", "kh"
    end
    on_arm do
      url "https://github.com/KeyHarbour/kh/releases/download/v#{version}/kh_#{version}_linux_arm64.tar.gz"
      sha256 "9bea59cde60abe574559bf3379e7049689ff11bd761852089f520caf5d7ee569"
      rename "kh_1.9.1_linux_arm64/kh", "kh"
    end
  end

  name "kh"
  desc "Official CLI for KeyHarbour — self-hosted Terraform state backend"
  homepage "https://keyharbour.ca"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kh"

  # No zap stanza required

end
