# This file was generated by GoReleaser. DO NOT EDIT.
cask "kh" do
  version "1.10.2"

  on_macos do
    on_intel do
      url "https://github.com/KeyHarbour/kh/releases/download/v#{version}/kh_#{version}_darwin_amd64.tar.gz"
      sha256 "53124bab2b5cf396034dc9f5cc25b17fecb5fcfe4509980eda1d3a0ebce3a919"
      rename "kh_1.10.2_darwin_amd64/kh", "kh"
    end
    on_arm do
      url "https://github.com/KeyHarbour/kh/releases/download/v#{version}/kh_#{version}_darwin_arm64.tar.gz"
      sha256 "9b0a8fc6f0ffbf7dc56f2f7a48dcd01e5afa5cc77bc2decf372b4f6c3b1dc532"
      rename "kh_1.10.2_darwin_arm64/kh", "kh"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/KeyHarbour/kh/releases/download/v#{version}/kh_#{version}_linux_amd64.tar.gz"
      sha256 "a0390a9e9ed8897afbe557de3cdc12ebdb1e8b55b3d613078bb0ea4ab8e655a2"
      rename "kh_1.10.2_linux_amd64/kh", "kh"
    end
    on_arm do
      url "https://github.com/KeyHarbour/kh/releases/download/v#{version}/kh_#{version}_linux_arm64.tar.gz"
      sha256 "205dcd7e9cb11f5516c2753df50c26a782b524a7a839bc5b6cbfd38b6c1750f1"
      rename "kh_1.10.2_linux_arm64/kh", "kh"
    end
  end

  name "kh"
  desc "Official CLI for KeyHarbour — self-hosted Terraform state backend"
  homepage "https://keyharbour.ca"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kh"

  # No zap stanza required

end
