# This file was generated by GoReleaser. DO NOT EDIT.
cask "kh" do
  version "1.9.0"

  on_macos do
    on_intel do
      url "https://github.com/KeyHarbour/kh/releases/download/v#{version}/kh_#{version}_darwin_amd64.tar.gz"
      sha256 "d5de4d7c4697e49ed323a0fa9922f7447ab557d8e3264650c1a5d82a101a92ed"
      rename "kh_1.9.0_darwin_amd64/kh", "kh"
    end
    on_arm do
      url "https://github.com/KeyHarbour/kh/releases/download/v#{version}/kh_#{version}_darwin_arm64.tar.gz"
      sha256 "1a892c7fc0393698761b8d0cbfcd021282a41f3f67acd7c31cfb0f019629e53c"
      rename "kh_1.9.0_darwin_arm64/kh", "kh"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/KeyHarbour/kh/releases/download/v#{version}/kh_#{version}_linux_amd64.tar.gz"
      sha256 "66e0139e1fd3b976dfc9501509611d31c675b0911c14655425cea2a4c8adc8c0"
      rename "kh_1.9.0_linux_amd64/kh", "kh"
    end
    on_arm do
      url "https://github.com/KeyHarbour/kh/releases/download/v#{version}/kh_#{version}_linux_arm64.tar.gz"
      sha256 "0354fe79bbcb966fa3ea74a847c3b5895277ce0d0fbec0a4eb7c26c6f66c25c3"
      rename "kh_1.9.0_linux_arm64/kh", "kh"
    end
  end

  name "kh"
  desc "Official CLI for KeyHarbour — self-hosted Terraform state backend"
  homepage "https://keyharbour.ca"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kh"

  # No zap stanza required

end
