# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kh < Formula
  desc "Official CLI for KeyHarbour — self-hosted Terraform state backend"
  homepage "https://keyharbour.ca"
  version "1.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/KeyHarbour/kh/releases/download/v1.7.0/kh_1.7.0_darwin_amd64.tar.gz"
      sha256 "1fab14695a528a9d63b78476f9ea22d1690941f43269c662e6e912b37a523bea"

      define_method(:install) do
        bin.install "kh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/KeyHarbour/kh/releases/download/v1.7.0/kh_1.7.0_darwin_arm64.tar.gz"
      sha256 "eeeed15817c7297f8e710ac73421790208243a983b2b00b1b829d63ba3924b35"

      define_method(:install) do
        bin.install "kh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/KeyHarbour/kh/releases/download/v1.7.0/kh_1.7.0_linux_amd64.tar.gz"
      sha256 "4e3d03e6e72cf3e122568e6458858366f7d7a513f23d24bc8003689f6e329f6b"
      define_method(:install) do
        bin.install "kh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/KeyHarbour/kh/releases/download/v1.7.0/kh_1.7.0_linux_arm64.tar.gz"
      sha256 "cb491de006a920eafc7257fd4af2f2957e824bf2b61c6682efd3e3c49b810d1e"
      define_method(:install) do
        bin.install "kh"
      end
    end
  end

  test do
    system "#{bin}/kh", "--version"
  end
end
