# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kh < Formula
  desc "Official CLI for KeyHarbour — self-hosted Terraform state backend"
  homepage "https://keyharbour.ca"
  version "1.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/KeyHarbour/kh/releases/download/v1.4.0/kh_1.4.0_darwin_amd64.tar.gz"
      sha256 "815c211c988bf8a4deb90957ede9d530358310dc133912e6af23878c5d4b6140"

      define_method(:install) do
        bin.install "kh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/KeyHarbour/kh/releases/download/v1.4.0/kh_1.4.0_darwin_arm64.tar.gz"
      sha256 "16c85b6205a73ec32cafe7ddeda0a10b63c2b45281bde4453bda5c008ae4a9b0"

      define_method(:install) do
        bin.install "kh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/KeyHarbour/kh/releases/download/v1.4.0/kh_1.4.0_linux_amd64.tar.gz"
      sha256 "5488f6431d2839d047f014336df18eb4a78ebb3765e71ec9dc1396c7e6569801"
      define_method(:install) do
        bin.install "kh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/KeyHarbour/kh/releases/download/v1.4.0/kh_1.4.0_linux_arm64.tar.gz"
      sha256 "a5949f9872af571b5b25f2ca1382ebc16cb9b88d8ef1bb37ab35e0bd56c0eaf1"
      define_method(:install) do
        bin.install "kh"
      end
    end
  end

  test do
    system "#{bin}/kh", "--version"
  end
end
