# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kh < Formula
  desc "Official CLI for KeyHarbour — self-hosted Terraform state backend"
  homepage "https://keyharbour.ca"
  version "1.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/KeyHarbour/kh/releases/download/v1.5.0/kh_1.5.0_darwin_amd64.tar.gz"
      sha256 "1041bdabdde8ee2b05ad1b8056fc9f49d20098196733ba7cf2f17371a5a2af6d"

      define_method(:install) do
        bin.install "kh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/KeyHarbour/kh/releases/download/v1.5.0/kh_1.5.0_darwin_arm64.tar.gz"
      sha256 "585f0320bbabc23d489f7d7a76ca501a45cfa629ee619dc1eb6ae78d47d27280"

      define_method(:install) do
        bin.install "kh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/KeyHarbour/kh/releases/download/v1.5.0/kh_1.5.0_linux_amd64.tar.gz"
      sha256 "ee6738a135680af270f037fe8d709938abd315500c5b8420e488aeb65c5db159"
      define_method(:install) do
        bin.install "kh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/KeyHarbour/kh/releases/download/v1.5.0/kh_1.5.0_linux_arm64.tar.gz"
      sha256 "59a93e4f434532346c92b56c2654cab41947cd0a53c7eb3566ec9a17813cc882"
      define_method(:install) do
        bin.install "kh"
      end
    end
  end

  test do
    system "#{bin}/kh", "--version"
  end
end
